apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
        - name: sidecar
          image: sidecar:latest
          imagePullPolicy: Never
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      # volumes:
      #   - name: podinfo
      #     downwardAPI:
      #       items:
      #         - path: "selector"
      #           fieldRef:
      #             fieldPath: deployment.selector

---

apiVersion: v1
kind: Pod
metadata:
  name: debugger
  labels:
    app: kubectl
spec:
  containers:
    - name: debugger
      image: kube-debugger
      imagePullPolicy: Never

